"use client";

import { useState } from "react";
import { compositions, goals } from "@/data/mock-dashboard";
import type { DashboardData } from "@/types/dashboard";
import { CoachNotes } from "@/components/CoachNotes";
import { CompositionCard, GoalCard, MatchCard, MetricCard, PlayerCard } from "@/components/Cards";
import { Sidebar } from "@/components/Sidebar";
import { Topbar } from "@/components/Topbar";

const titles: Record<string, string> = { overview: "Team Overview", players: "Player Development", matches: "Match Review", compositions: "Composition Library", goals: "Weekly Goals", notes: "Coach Notes" };

export function Dashboard({ players, matches, teamMetrics, dataStatus, dataMessage }: DashboardData) {
  const [activeView, setActiveView] = useState("overview");
  function setView(view: string) { setActiveView(view); window.scrollTo({ top: 0, behavior: "smooth" }); }

  return <div className="app-shell"><Sidebar activeView={activeView} onViewChange={setView} /><main className="main"><Topbar title={titles[activeView]} />
    <section id="overview" className={`view ${activeView === "overview" ? "active" : ""}`}><div className="notice"><strong>{dataStatus === "live" ? "Live Riot data:" : dataStatus === "empty" ? "Waiting for Riot data:" : "Riot data unavailable:"}</strong> {dataMessage}</div><div className="metric-grid">{teamMetrics.map((metric) => <MetricCard metric={metric} key={metric.label} />)}</div><div className="dashboard-grid"><article className="panel strengths-panel"><div className="panel-head"><h2>Coaching Analysis</h2><span>Manual review</span></div><div className="coach-callout"><span className="callout-icon">i</span><p>Riot match records provide performance statistics, not reliable coaching conclusions. Add reviewed findings in <b>Coach Notes</b> after watching the games.</p></div></article><article className="panel chart-panel"><div className="panel-head"><h2>Gold Difference</h2><span>Not imported</span></div><div className="coach-callout"><span className="callout-icon">i</span><p>Timeline data is not currently imported, so no gold-difference chart is shown. Fabricating one would be prettier, but less useful.</p></div></article><article className="panel recent-panel"><div className="panel-head"><h2>Recent Player Matches</h2><button className="text-button" onClick={() => setView("matches")}>View all</button></div><div>{matches.slice(0, 4).map((match) => <div className="match-row" key={`${match.when}-${match.composition}`}><div><span className={`result ${match.result === "Victory" ? "positive" : "negative"}`}>{match.result}</span><span>{match.duration}</span></div><div><b>{match.composition}</b><span>{match.when}</span></div><div className="score"><b>{match.score}</b><span>Player K/D/A</span></div></div>)}</div></article></div><article className="panel roster-panel"><div className="panel-head"><h2>CAD Earth Roster</h2><span>Competitive lineup</span></div><div className="table-wrap"><table><thead><tr><th>Player</th><th>Role</th><th>Sample</th><th>Win Rate</th><th>KDA</th><th>CS / Min</th><th>Avg K+A</th><th>Primary Goal</th></tr></thead><tbody>{players.map((player) => <tr key={player.id}><td><span className="player-name">{player.id}</span></td><td><span className="role-tag">{player.role}</span></td><td>{player.rank}</td><td className="positive">{player.winRate}</td><td>{player.kda}</td><td>{player.csPerMinute}</td><td>{player.killParticipation}</td><td>{player.goal}</td></tr>)}</tbody></table></div></article></section>
    <section id="players" className={`view ${activeView === "players" ? "active" : ""}`}><div className="section-intro"><h2>Player Development</h2><p>Role-specific metrics, champion pools, and coaching priorities.</p></div><div className="player-grid">{players.map((player) => <PlayerCard key={player.id} player={player} />)}</div></section>
    <section id="matches" className={`view ${activeView === "matches" ? "active" : ""}`}><div className="section-intro"><h2>Match Review</h2><p>Imported individual player results and performance snapshots.</p></div><div className="match-grid">{matches.map((match) => <MatchCard key={`${match.when}-${match.composition}`} match={match} />)}</div></section>
    <section id="compositions" className={`view ${activeView === "compositions" ? "active" : ""}`}><div className="section-intro"><h2>Composition Library</h2><p>Saved drafts rated for engage, peel, scaling, and damage balance.</p></div><div className="composition-grid">{compositions.map((composition) => <CompositionCard key={composition.name} composition={composition} />)}</div></section>
    <section id="goals" className={`view ${activeView === "goals" ? "active" : ""}`}><div className="section-intro"><h2>Weekly Goals</h2><p>One clear target per player. Revolutionary restraint.</p></div><div className="goal-grid">{goals.map((goal) => <GoalCard key={goal.playerId} goal={goal} />)}</div></section>
    <section id="notes" className={`view ${activeView === "notes" ? "active" : ""}`}><div className="section-intro"><h2>Coach Notes</h2><p>Coach notes are publicly readable and backed by Supabase; editing requires admin login.</p></div><CoachNotes /></section>
  </main></div>;
}
