create table if not exists public.riot_matches (
  match_id text primary key,
  queue_id integer,
  game_mode text,
  game_type text,
  game_version text,
  game_start_time timestamptz,
  game_end_time timestamptz,
  game_duration_seconds integer not null default 0
    check (game_duration_seconds >= 0),
  imported_at timestamptz not null default now()
);

create table if not exists public.riot_player_matches (
  id bigint generated by default as identity primary key,
  match_id text not null
    references public.riot_matches(match_id)
    on delete cascade,
  puuid text not null,
  riot_id text not null,
  roster_role text not null,
  participant_id integer,
  team_id integer,
  champion_id integer,
  champion_name text,
  team_position text,
  win boolean not null,
  kills integer not null default 0,
  deaths integer not null default 0,
  assists integer not null default 0,
  total_minions_killed integer not null default 0,
  neutral_minions_killed integer not null default 0,
  gold_earned integer not null default 0,
  vision_score integer not null default 0,
  total_damage_dealt_to_champions integer not null default 0,
  damage_dealt_to_objectives integer not null default 0,
  time_played_seconds integer not null default 0,
  created_at timestamptz not null default now(),
  unique (match_id, puuid)
);

create index if not exists riot_matches_start_time_idx
  on public.riot_matches (game_start_time desc);

create index if not exists riot_player_matches_puuid_idx
  on public.riot_player_matches (puuid);

create index if not exists riot_player_matches_riot_id_idx
  on public.riot_player_matches (riot_id);

create index if not exists riot_player_matches_match_id_idx
  on public.riot_player_matches (match_id);

alter table public.riot_matches enable row level security;
alter table public.riot_player_matches enable row level security;

drop policy if exists "Public can read Riot matches"
  on public.riot_matches;

create policy "Public can read Riot matches"
  on public.riot_matches
  for select
  using (true);

drop policy if exists "Admins can manage Riot matches"
  on public.riot_matches;

create policy "Admins can manage Riot matches"
  on public.riot_matches
  for all
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.is_admin = true
    )
  )
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.is_admin = true
    )
  );

drop policy if exists "Public can read Riot player matches"
  on public.riot_player_matches;

create policy "Public can read Riot player matches"
  on public.riot_player_matches
  for select
  using (true);

drop policy if exists "Admins can manage Riot player matches"
  on public.riot_player_matches;

create policy "Admins can manage Riot player matches"
  on public.riot_player_matches
  for all
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.is_admin = true
    )
  )
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.is_admin = true
    )
  );

grant select on public.riot_matches
  to anon, authenticated;

grant select on public.riot_player_matches
  to anon, authenticated;

grant insert, update, delete on public.riot_matches
  to authenticated;

grant insert, update, delete on public.riot_player_matches
  to authenticated;

grant usage, select on sequence public.riot_player_matches_id_seq
  to authenticated;